### ISSUE TITLE
License

### ISSUE THREAD

**Issue by boykoc** [ontario-digital/Digital-Service-Standard#2]
Might be good to add a license to this? Might make it easier for others to fork and adapt for their own jurisdictions/use.

Here's a [sample license](https://github.com/alphagov/govuk-aws/blob/master/LICENSE) from GovUK repo.

**Comment by katekalcevich** [comment]
We're considering using our own Open Government license for this.

**Comment by ghost** [comment]
Added the license: https://github.com/ontario-digital/Digital-Service-Standard/commit/9eb59f9a662528a6ce2609524443b0ba1f395057
