### ISSUE TITLE
"assisted digital support model"

### ISSUE THREAD

**Issue by mgifford** [ontario-digital/Digital-Service-Standard#31]
I don't think that this is a common term outside of the UK.  Maybe even outside of the GDS.  A reference to the assisted digital support model is needed and probably a definition too:
https://www.gov.uk/service-manual/helping-people-to-use-your-service/assisted-digital-support-introduction

Perhaps this will make sense in context of the larger Digital Service Standard.

**Comment by ongov** [comment]
We're still working on creating supports for the Digital Service Standard and this is an area we know we have to tackle. Thanks for bringing it up. Look for assisted digital resources in an upcoming release.
