### ISSUE TITLE
Add guidelines for tables in : https://www.ontario.ca/page/ontarioca-style-guide

### ISSUE THREAD

**Issue by Rajakavitha1** [ontario-digital/Digital-Service-Standard#58]
We have some great guidelines for content in https://www.ontario.ca/page/ontarioca-style-guide. However, I was wondering if we could add some guidelines around tables. 
For example, if a table has a caption, then the screen reader will then say “Table with 3 rows and 4 columns, Monthly Budget” or something to that effect. Without this, the screen reader will just start reading off the values inside the table, which is going to be frustrating and not super useful. Imagine reading an entire table cell by cell and then piecing together what the table is trying to tell you.

**Comment by jeramin** [comment]
Hi, thanks for pointing this out! The Government of Ontario has another guide for design elements across all digital products (not just Ontario.ca!), called the [Ontario Design Guide](https://www.ontario.ca/page/ontario-design-guide), where we go into more details on page elements, [including tables](https://www.ontario.ca/page/ontario-design-guide#section-12). 

I hope this is helpful!
